import { Inter } from "next/font/google";
import "./globals.css";
import Header from '../app/components/header/header';
import Header2 from './components/header2/header2';
import Footer1 from './components/footer/footer1';
import '@fortawesome/fontawesome-svg-core/styles.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
    <script id="chatway" async={true} src="https://cdn.chatway.app/widget.js?id=evTLAzR0Ancg"></script>
    <script id="pixel-chaty" async={true} src="https://cdn.chaty.app/pixel.js?id=unBeUuC3"></script>
    <link rel='icon' href='/logo-11.ico'/>
    </head>
      <body className={inter.className}>
        <Header/>
        <Header2/>
          {children}
        <Footer1/>
      </body>
    </html>
  );
}
